version: '3.7'

x-airflow-common: &airflow-common
  image: airflow-custom:2.8.1
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://airflow:airflow@mysql:3306/retail_analytics_airflow
    AIRFLOW__CORE__FERNET_KEY: 'AMONgARy35jI4Xz0ZUqSh1K4MI4hTqo7WW93xaYCRnU='
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__WEBSERVER__RBAC: 'true'
  volumes:
    - ./airflow-docker/airflow-docker/dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./scripts:/opt/airflow/scripts
    - ./utils:/opt/airflow/utils
    - ./data:/opt/airflow/data
    - ./requirements.txt:/requirements.txt
    - ./create_admin.sh:/opt/airflow/create_admin.sh
  depends_on:
    mysql:
      condition: service_healthy

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: retail_analytics_airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 10

  airflow-init:
    <<: *airflow-common
    entrypoint: bash -c "airflow db init"

  webserver:
    <<: *airflow-common
    ports:
      - "8085:8080"
    entrypoint: bash -c "airflow db upgrade && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com && airflow webserver"

  scheduler:
    <<: *airflow-common
    entrypoint: bash -c "airflow scheduler"
    depends_on:
    - mysql

volumes:
  mysql_data: {}
